# Generated by Django 3.1.3 on 2021-03-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='franquicia',
            name='expression',
            field=models.CharField(default='', max_length=100, verbose_name='Expresion'),
        ),
    ]
