# Generated by Django 3.1.3 on 2021-03-27 20:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_franquicia_expression'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('token_verificacion', models.CharField(auto_created=True, default=uuid.uuid4, max_length=100)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=80, verbose_name='Correo')),
                ('vericado', models.BooleanField(default=False, verbose_name='Verificado')),
            ],
        ),
    ]
