# Generated by Django 3.1.3 on 2021-03-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210327_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta',
            name='numero',
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='token',
            field=models.CharField(default='', max_length=200, verbose_name='Token'),
        ),
    ]
