# Generated by Django 3.1.3 on 2021-03-27 23:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210327_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='token',
            field=models.CharField(default=None, max_length=200, verbose_name='Token'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4),
        ),
    ]
