# Generated by Django 3.1.3 on 2021-03-27 23:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210327_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='token_verificacion',
            field=models.CharField(auto_created=True, default=uuid.uuid4, max_length=100, null=True),
        ),
    ]
