# Generated by Django 3.1.3 on 2021-03-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210327_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='token',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='Token'),
        ),
    ]
