# Generated by Django 3.1.3 on 2021-03-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210327_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='token_fecha_creacion',
            field=models.DateTimeField(default=None),
        ),
    ]
