# Generated by Django 3.1.3 on 2021-03-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_tarjeta_token_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='token',
            field=models.CharField(default=None, max_length=200, verbose_name='Token'),
        ),
    ]
